### ISSUE TITLE
Missing assembly references again?

### ISSUE THREAD

**Issue by grobm** [aestheticinteractive/Hover-VR-Interface-Kit#26]
I am getting reference errors again in the latest code when I pull it from the repository? 

ErrO CS0234 when working in Unity 4.6f or Unity 5.1. 

Error example: 
Assets/Hover/Demo/BoardKeys/CastItems/DemoBaseListener.cs(2,13): error CS0234: The type or namespace name `Board' does not exist in the namespace`Hover'. Are you missing an assembly reference?

Steps to reproduce:
Pulling code from repo and then importing into Unity. 

It's been a while... Am I missing a step?

**Comment by grobm** [comment]
![screen shot 2015-05-24 at 8 33 19 pm](https://cloud.githubusercontent.com/assets/10155745/7790406/8803d2fa-0254-11e5-8897-f292fd88d266.png)

**Comment by grobm** [comment]
Getting this after doing all the installation instructions:

Internal compiler error. See the console log for more information. output was:
Unhandled Exception: System.Reflection.ReflectionTypeLoadException: The classes in the module cannot be loaded.
  at (wrapper managed-to-native) System.Reflection.Assembly:GetTypes (bool)
  at System.Reflection.Assembly.GetTypes () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.RootNamespace.ComputeNamespaces (System.Reflection.Assembly assembly, System.Type extensionType) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.RootNamespace.ComputeNamespace (Mono.CSharp.CompilerContext ctx, System.Type extensionType) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.GlobalRootNamespace.ComputeNamespaces (Mono.CSharp.CompilerContext ctx) [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.LoadReferences () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.Compile () [0x00000] in <filename unknown>:0 
  at Mono.CSharp.Driver.Main (System.String[] args) [0x00000] in <filename unknown>:0

**Comment by ddutchie** [comment]
Try one of the releases?

**Comment by ilanb** [comment]
Hi, same problem for me, tried all release on unity 4.5.6 and 5.0.1

Tried to rebuild too.

Assets/Hover/Demo/BoardKeys/PrefabBuilders/DemoPrefabSplitKeyboard.cs(12,30): error CS0246: The type or namespace name `HoverboardLayout' could not be found. Are you missing a using directive or an assembly reference?

**Comment by zachkinstner** [comment]
@grobm, @ddutchie, @ilanb -- sorry you're having issues here! I can try to help.

First, please note that the [releases](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/releases) are the official versions to use. The `master` branch of the source code currently contains a variety of changes and updates that are only minimally tested at this point.

The error message in the screenshot is related to `UnityEngine.dll` being included manually within your Unity project. My guess is that you've included the entire Hover VR repository within your Unity project. However, this is not how the Hover VR project is structured. Everything in the [`/Core`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/master/Core) directory is meant to be built via Visual Studio and/or MonoDevelop. The result of this build (the Hover VR DLL files) are then used by the Unity project. The [`/Core/Packages/Unity`](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/tree/master/Core/Packages/Unity) directory includes copies of the Unity DLLs, which (I think) is the source of your `UnityEngine.dll` error message.

If you've previously copied the entire Hover VR repository into your Unity project, then please delete _all_ of those files from the project before trying to use the release builds. The release builds contain everything you'll need to use Hover VR.

**Comment by zachkinstner** [comment]
I created a new [Getting Started](https://github.com/aestheticinteractive/Hover-VR-Interface-Kit/wiki/Getting-Started) wiki page that contains some of these details.

**Comment by zachkinstner** [comment]
I have closed this issue for now. Please let me know if my notes above have not resolved the issue.
